# Generated by Django 2.2.23 on 2021-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_reviews', '0003_auto_20210927_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communicationScale',
            field=models.IntegerField(verbose_name='Communication Skills: Rate 1-10'),
        ),
        migrations.AlterField(
            model_name='review',
            name='experienceScale',
            field=models.IntegerField(verbose_name='Experience: Rate 1-10'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gpaScale',
            field=models.IntegerField(verbose_name='GPA: Rate 1-10'),
        ),
        migrations.AlterField(
            model_name='review',
            name='technicalScale',
            field=models.IntegerField(verbose_name='Technical Skills: Rate 1-10'),
        ),
    ]
